language: node_js
node_js:
- 6.10.3
before_script:
- npm run build
deploy:
  api_key:
    secure: h9k+kJnWvHipfwHe/uLGfyh1qQh+XcIMcH1UsgRljoVRHGA9kt3Vj7g0i9fjkVEpvYENTwW4oTWiuEfEDVHTRqP9S0crtd+aKpYGPRtPvWsbUqRkfMhIBaXWElo0aMZ9/vle9iVFh+jJZDO4JdftGCbcPqPYuCj8HvTYFZY+sAclZCDEm8WBEMPsNKQR7IQBHLHm9tBjNYvKHhw9b8RRmzAUaAjq2W2RZPAmwIaYXFgMFN4Q4cHLdn+Wyfqb/HDLJz67uKnahp+3Nz7pGCvnh/p+DB9o9R/9esj4SNPTBs/3+VqFhbkqjZ/0/E5Z+IYnd6+6fXT1Cp2u7hAdazxWFOyb1Td6YUFIzIDSQFL3TrRDoA25VJH+my6tsjKcwDGuYmVE7nrYtLpsQc/vfz1yWlkt16ieEb3mPkf41dZ/A0ZBS6J7fLv0TVrxoucCmBnWSegl35fow6ZB/Rt8VnpE2RJk1zQQISXGNStBvMaG+Bdf3sxN5G/8RZi/ODLYGOWGxsPuOpNawOmZu5nau6nyUgkPrS/B+/Aqog/cYu8Tq17EqdhMV640DtW4ulOBgYjqAaUcjOjenRmi8sm6sEx+Lk1Z1RdSMmAgvQOcdHMf/eoj5D3nGNoqxYfPEGmN4q81fB6vGK0XTc7McQirh8ivRFH5aBtirfAYFItotpkSWkY=
  email: vladimirmorulus@gamil.com
  provider: npm
  skip_cleanup: true
  before_script: npm run prepublish
  on:
    branch:
    - master
